// Objective-C API for talking to github.com/DFXswiss/bitbox_flutter/api Go package.
//   gobind -lang=objc github.com/DFXswiss/bitbox_flutter/api
//
// File is generated by gobind. Do not edit.

#ifndef __Api_H__
#define __Api_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol ApiGoDeviceInfoInterface;
@class ApiGoDeviceInfoInterface;
@protocol ApiGoReadWriteCloserInterface;
@class ApiGoReadWriteCloserInterface;

@protocol ApiGoDeviceInfoInterface <NSObject>
- (NSString* _Nonnull)identifier;
- (long)interface;
- (BOOL)isBluetooth;
- (id<ApiGoReadWriteCloserInterface> _Nullable)open:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)product;
- (long)productID;
- (NSString* _Nonnull)serial;
- (long)usagePage;
- (long)vendorID;
@end

@protocol ApiGoReadWriteCloserInterface <NSObject>
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)read:(long)n error:(NSError* _Nullable* _Nullable)error;
- (BOOL)write:(NSData* _Nullable)p0 n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
@end

FOUNDATION_EXPORT NSData* _Nullable ApiBTCSignMessage(long coinType, NSString* _Nullable keypath, NSData* _Nullable msg);

FOUNDATION_EXPORT NSString* _Nonnull ApiBTCSignPSBT(long coinType, NSString* _Nullable psbtStr);

FOUNDATION_EXPORT NSString* _Nonnull ApiBTCXPub(long coinType, NSString* _Nullable keypath, long addressType, BOOL display);

FOUNDATION_EXPORT void ApiChannelHashVerify(BOOL ok);

// skipped function DeviceInfo with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull ApiETHGetAddress(long chainId, NSString* _Nullable keypath, long outputType, BOOL display, NSData* _Nullable contractAddress);

FOUNDATION_EXPORT NSData* _Nullable ApiETHSignEIP1559(long chainId, NSString* _Nullable keypath, long nonce, NSString* _Nullable maxPriorityFeePerGas, NSString* _Nullable maxFeePerGas, long gasLimit, NSData* _Nullable recipient, NSString* _Nullable value, NSData* _Nullable data, long recipientAddressCase);

FOUNDATION_EXPORT NSData* _Nullable ApiETHSignMessage(long chainId, NSString* _Nullable keypath, NSData* _Nullable msg);

FOUNDATION_EXPORT NSData* _Nullable ApiETHSignRPLTx(long chainId, NSString* _Nullable keypath, NSString* _Nullable encodedTx, BOOL isEIP1559);

FOUNDATION_EXPORT NSData* _Nullable ApiETHSignTransaction(long chainId, NSString* _Nullable keypath, long nonce, NSString* _Nullable gasPrice, long gasLimit, NSData* _Nullable recipient, NSString* _Nullable value, NSData* _Nullable data, long recipientAddressCase);

FOUNDATION_EXPORT NSData* _Nullable ApiETHSignTypedMessage(long chainId, NSString* _Nullable keypath, NSData* _Nullable jsonMsg);

FOUNDATION_EXPORT NSString* _Nonnull ApiGetChannelHash(void);

FOUNDATION_EXPORT void ApiGetDevice(id<ApiGoReadWriteCloserInterface> _Nullable device);

/**
 * GetDeviceWithInfo is like GetDevice but accepts version and product info for Bluetooth connections.
version should be like "v9.25.0", product should be like "bb02p-multi" or "bb02p-btconly".
 */
FOUNDATION_EXPORT void ApiGetDeviceWithInfo(id<ApiGoReadWriteCloserInterface> _Nullable device, NSString* _Nullable versionStr, NSString* _Nullable productStr);

FOUNDATION_EXPORT NSData* _Nullable ApiGetMasterFingerprint(void);

FOUNDATION_EXPORT BOOL ApiInitDevice(void);

FOUNDATION_EXPORT BOOL ApiSupportsBluetooth(void);

FOUNDATION_EXPORT BOOL ApiSupportsERC20(NSString* _Nullable contractAddress);

FOUNDATION_EXPORT BOOL ApiSupportsETH(long chainId);

FOUNDATION_EXPORT BOOL ApiSupportsLTC(void);

@class ApiGoDeviceInfoInterface;

@class ApiGoReadWriteCloserInterface;

/**
 * GoDeviceInfoInterface adapts usb.DeviceInfo's Open method to return the adapted ReadWriteCloser.
 */
@interface ApiGoDeviceInfoInterface : NSObject <goSeqRefInterface, ApiGoDeviceInfoInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (NSString* _Nonnull)identifier;
- (long)interface;
- (BOOL)isBluetooth;
- (id<ApiGoReadWriteCloserInterface> _Nullable)open:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)product;
- (long)productID;
- (NSString* _Nonnull)serial;
- (long)usagePage;
- (long)vendorID;
@end

/**
 * GoReadWriteCloserInterface adapts io.ReadWriteCloser's Read method to return the byte read byte slice
instead of the .Read([]byte) pattern. This is as gomobile bind seems to make a copy of passed
slices instead of writing directly to it, so the byte slice never makes it back to Go-land.
 */
@interface ApiGoReadWriteCloserInterface : NSObject <goSeqRefInterface, ApiGoReadWriteCloserInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)read:(long)n error:(NSError* _Nullable* _Nullable)error;
- (BOOL)write:(NSData* _Nullable)p0 n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
@end

#endif
